openapi: 3.0.0

info:
  version: 1.0.0
  title: ""

servers:
  - url: https://api.pubg.com/shards/{platform}
    variables:
      "platform":
        enum:
        - "kakao"
        - "psn"
        - "stadia"
        - "steam"
        - "xbox"
        default: steam

security:
  - ApiKeyAuth: []

paths:
  /clans/{clanId}:
    $ref: './paths/index.yml#/clan'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    clan:
      $ref: 'schemas/index.yml#/clan'
