openapi: 3.0.0

info:
  version: 1.0.0
  title: ""
  description: Authorization is not required for the /matches endpoint because it is not rate-limited.
servers:
  - url: https://api.pubg.com/shards/{platform}
    variables:
      "platform":
        enum:
        - "console"
        - "kakao"
        - "psn"
        - "stadia"
        - "steam"
        - "tournament"
        - "xbox"
        default: steam
paths:
  /matches/{id}:
    $ref: './paths/index.yml#/match'
components:
  schemas:
    match:
      $ref: 'schemas/index.yml#/match'
    roster:
      $ref: 'schemas/index.yml#/roster'
    participant:
      $ref: 'schemas/index.yml#/participant'
    asset:
      $ref: 'schemas/index.yml#/asset'
