openapi: 3.0.0

info:
  version: 1.0.0
  title: ""
  description: Notes:<br>
    - Both "https://api.pubg.com/shards/{platform}" and "https://api.pubg.com/shards/{platform-region}" can be used to get matches.<br>
    - Any property with \"N/A\" as its description is not currently in use."
servers:
  - url: https://api.pubg.com/shards/{platform-region}
    variables:
      "platform-region":
        enum:
        - "xbox-as"
        - "xbox-eu"
        - "xbox-na"
        - "xbox-oc"
        - "xbox-sa"
        - "pc-krjp"
        - "pc-jp"
        - "pc-na"
        - "pc-eu"
        - "pc-ru"
        - "pc-oc"
        - "pc-kakao"
        - "pc-sea"
        - "pc-sa"
        - "pc-as"
        - "pc-tournament"
        default: pc-na
  - url: https://api.pubg.com/shards/{platform}
    variables:
      "platform":
        enum:
        - "kakao"
        - "steam"
        default: steam

security:
  - ApiKeyAuth: []

paths:
  /matches/{id}:
    $ref: './paths/index.yml#/match'

components:
  schemas:
    match:
      $ref: 'schemas/index.yml#/match'
    roster:
      $ref: 'schemas/index.yml#/roster'
    participant:
      $ref: 'schemas/index.yml#/participant'
    asset:
      $ref: 'schemas/index.yml#/asset'
