openapi: 3.0.0

info:
  version: 1.0.0
  title: ""

servers:
  - url: https://api.pubg.com/shards/{platform-region}
    variables:
      "platform-region":
        enum:
        - "xbox-as"
        - "xbox-eu"
        - "xbox-na"
        - "xbox-oc"
        - "pc-krjp"
        - "pc-jp"
        - "pc-na"
        - "pc-eu"
        - "pc-ru"
        - "pc-oc"
        - "pc-kakao"
        - "pc-sea"
        - "pc-sa"
        - "pc-as"
        default: pc-na

security:
  - ApiKeyAuth: []

paths:
  /samples:
    $ref: './paths/index.yml#/samples'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    sample:
      $ref: 'schemas/index.yml#/sample'
