openapi: 3.0.0

info:
  version: 1.0.0
  title: ""

servers:
  - url: https://api.playbattlegrounds.com/

security:
  - ApiKeyAuth: []

paths:
  /tournaments:
    $ref: './paths/index.yml#/tournamentList'

  /tournaments/{id}:
    $ref: './paths/index.yml#/tournaments'

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      description: "Enter your API key here to be used with the interactive documentation!"
      scheme: bearer
      bearerFormat: JWT

  schemas:
    tournament:
      $ref: 'schemas/index.yml#/tournament'
